/* eslint-disable no-shadow */
import { TagsTypes } from 'store';

export const TagsColors: TagsTypes.TagsColorType[] = [
  'default',
  'magenta',
  'pink',
  'red',
  'error',
  'volcano',
  'orange',
  'gold',
  'warning',
  'yellow',
  'lime',
  'success',
  'green',
  'cyan',
  'processing',
  'blue',
  'geekblue',
  'purple',
];

export enum TagsBorderColors {
  default = '#000',
  magenta = '#c41d7f',
  pink = '#c41d7f',
  red = '#cf1322',
  error = '#ff4d4f',
  volcano = '#d4380d',
  orange = '#d46b08',
  gold = '#d48806',
  warning = '#faad14',
  yellow = '#d4b106',
  lime = '#7cb305',
  success = '#52c41a',
  green = '#389e0d',
  cyan = '#08979c',
  processing = '#1890ff',
  blue = '#096dd9',
  geekblue = '#1d39c4',
  purple = '#531dab',
}

export enum TagsFillColors {
  default = '#fff',
  magenta = '#fff0f6',
  pink = '#fff0f6',
  red = '#fff1f0',
  error = '#fff2f0',
  volcano = '#fff2e8',
  orange = '#fff7e6',
  gold = '#fffbe6',
  warning = '#fffbe6',
  yellow = '#feffe6',
  lime = '#fcffe6',
  success = '#f6ffed',
  green = '#f6ffed',
  cyan = '#e6fffb',
  processing = '#e6f7ff',
  blue = '#e6f7ff',
  geekblue = '#f0f5ff',
  purple = '#f9f0ff',
}
